#!/usr/bin/python
import os,sys
Offline_nodes = int(os.popen('sinfo -R --state=down|tail -n +2|wc -l').read())
if Offline_nodes==0:
	print "OK - All Nodes Operational:"
	sys.exit(0)
elif Offline_nodes>=1:
    print "CRITICAL - Offline Nodes:",Offline_nodes
	sys.exit(1)
else:
	print "UNKNOWN - Offline Nodes:",Offline_nodes
	sys.exit(3)
